/*global jQuery */
/*!	
* Responsive-Portfolio-Gallery
*
* Copyright 2011, http://www.freshdesignweb.com/
* Released under the WTFPL license 
*
*/

(function( $, undefined ) {$.EmgHoverDir=function(e,t){this.$el=$(t);this._init(e)};$.EmgHoverDir.defaults={hoverDelay:0,reverse:false};$.EmgHoverDir.prototype={_init:function(e){this.options=$.extend(true,{},$.EmgHoverDir.defaults,e);this._loadEvents()},_loadEvents:function(){var e=this;this.$el.bind("mouseenter.emghoverdir, mouseleave.emghoverdir",function(t){var n=$(this),r=t.type,i=n.find("article"),s=e._getDir(n,{x:t.pageX,y:t.pageY}),o=e._getClasses(s);i.removeClass();if(r==="mouseenter"){i.hide().addClass(o.from);clearTimeout(e.tmhover);e.tmhover=setTimeout(function(){i.show(0,function(){$(this).addClass("da-animate").addClass(o.to)})},e.options.hoverDelay)}else{i.addClass("da-animate");clearTimeout(e.tmhover);i.addClass(o.from)}})},_getDir:function(e,t){var n=e.width(),r=e.height(),i=(t.x-e.offset().left-n/2)*(n>r?r/n:1),s=(t.y-e.offset().top-r/2)*(r>n?n/r:1),o=Math.round((Math.atan2(s,i)*(180/Math.PI)+180)/90+3)%4;return o},_getClasses:function(e){var t,n;switch(e){case 0:!this.options.reverse?t="da-slideFromTop":t="da-slideFromBottom";n="da-slideTop";break;case 1:!this.options.reverse?t="da-slideFromRight":t="da-slideFromLeft";n="da-slideLeft";break;case 2:!this.options.reverse?t="da-slideFromBottom":t="da-slideFromTop";n="da-slideTop";break;case 3:!this.options.reverse?t="da-slideFromLeft":t="da-slideFromRight";n="da-slideLeft";break}return{from:t,to:n}}};var logError=function(e){if(this.console){console.error(e)}};$.fn.emghoverdir=function(e){if(typeof e==="string"){var t=Array.prototype.slice.call(arguments,1);this.each(function(){var n=$.data(this,"emghoverdir");if(!n){logError("cannot call methods on emghoverdir prior to initialization; "+"attempted to call method '"+e+"'");return}if(!$.isFunction(n[e])||e.charAt(0)==="_"){logError("no such method '"+e+"' for emghoverdir instance");return}n[e].apply(n,t)})}else{this.each(function(){var t=$.data(this,"emghoverdir");if(!t){$.data(this,"emghoverdir",new $.EmgHoverDir(e,this))}})}return this}})( jQuery );

jQuery(function(){jQuery(window).scroll(function(){if(jQuery("#mbCenter").size()>0){var e=parseInt(jQuery(document).scrollTop());var t=jQuery("#mbCenter").offset();var n=parseInt(t.top+jQuery("#mbCenter").height()+90-e);var r=jQuery(window).height()-n;if(e<t.top-90){setTimeout(function(){jQuery("#mbCenter").stop().animate({top:jQuery(window).scrollTop()+340},500)},150)}if(r>1&&jQuery(window).height()<jQuery("#mbCenter").height()-90){setTimeout(function(){jQuery("#mbCenter").stop().animate({top:t.top+340},500)},150)}else if(r>1&&jQuery(window).height()>jQuery("#mbCenter").height()+90){setTimeout(function(){jQuery("#mbCenter").stop().animate({top:jQuery(window).scrollTop()+340},500)},150)}}})})

/* Image hover */
jQuery(function($){$("div.da-thumbs").emghoverdir();$(".emgfittext").fitText(1.2,{ maxFontSize: "12px" });});

/* ISOTOPE */
var fodr = [];
jQuery(window).load(function(){jQuery(function(e){if (typeof(fodr[0]) == 'undefined' || fodr[0] == null){fodr[0] = "*";}if(!jQuery.isNumeric(jQuery(".pagwrap").attr("id"))){e.Isotope.prototype._getCenteredMasonryColumns=function(){this.width=this.element.width();var e=this.element.parent().width();var t=this.options.masonry&&this.options.masonry.columnWidth||this.$filteredAtoms.outerWidth(true)||e;var n=Math.floor(e/t);n=Math.max(n,1);this.masonry.cols=n;this.masonry.columnWidth=t};e.Isotope.prototype._masonryReset=function(){this.masonry={};this._getCenteredMasonryColumns();var e=this.masonry.cols;this.masonry.colYs=[];while(e--){this.masonry.colYs.push(0)}};e.Isotope.prototype._masonryResizeChanged=function(){var e=this.masonry.cols;this._getCenteredMasonryColumns();return this.masonry.cols!==e};e.Isotope.prototype._masonryGetContainerSize=function(){var e=0,t=this.masonry.cols;while(--t){if(this.masonry.colYs[t]!==0){break}e++}return{height:Math.max.apply(Math,this.masonry.colYs),width:(this.masonry.cols-e)*this.masonry.columnWidth}};var t=e(".easycontainer");var n=e(window);t.isotope({itemSelector:".easyitem",filter:fodr[0],transformsEnabled:true,onLayout:function(){n.trigger("scroll")}});var r=e("#emgoptions .emgoption-set"),i=r.find("a");i.click(function(){var n=e(this);if(n.hasClass("selected")){return false}var r=n.parents(".emgoption-set");r.find(".selected").removeClass("selected");n.addClass("selected");var i={},s=r.attr("data-option-key"),o=n.attr("data-option-value");o=o==="false"?false:o;i[s]=o;if(s==="layoutMode"&&typeof changeLayoutMode==="function"){changeLayoutMode(n,i)}else{t.isotope(i)}return false});jQuery(".pagwrap").fadeIn(1000);jQuery(".emgajxloader").hide();jQuery(".easycontainer").isotope( 'reLayout' );jQuery(".emgfittext").fitText(1.2,{ maxFontSize: "12px" });}})});

/* jPages & Lazyload */
jQuery(function(e){function t(t,n,r){if(e(this).next("p").hasClass("emgfittext")&&e(this).next("p").text().length>0){e(this).next("p").fadeIn(1e3)}if(e(this).parent().find("p").hasClass("emgfittext")&&e(this).parent().find("p").text().length>0){e(this).parent().find("p").fadeIn("fast")}if(e(this).parent().parent().prev().hasClass("emg-badges")){e(this).parent().parent().prev("span.emg-badges").fadeIn(2e3)}if(e(this).parent().prev().hasClass("emg-badges")){e(this).parent().prev("span.emg-badges").fadeIn(2e3)}if(e(this).parent().parent().hasClass("preloaderview")){e(this).parent().parent().removeClass("preloaderview")}if(e(this).parent().parent().parent().hasClass("preloaderview")){e(this).parent().parent().parent().removeClass("preloaderview")}e(this).css("height", "100%");e(this).css("max-height", "100%");e(this).css("width", "100%");}if(e.isNumeric(e(".pagwrap").attr("id"))){e(".iehand img").lazyload({event:"turnPage",load:t,effect:"fadeIn",failure_limit:Math.max(e(".iehand img").length-1,0),effectspeed:900});e("div.emg-pag-holder").emgPag({containerID:"emgpagntn",animation:EasyM.pageffect,perPage:parseInt(e(".pagwrap").attr("id")),callback:function(t,n){n.showing.find("img").trigger("turnPage");n.oncoming.find("img").trigger("turnPage");e("#pag-legend1").html("Page "+t.current+" of "+t.count);e("#pag-legend2").html(n.range.start+" - "+n.range.end+" of "+n.count)}})}if(!e.isNumeric(e(".pagwrap").attr("id"))){e(".iehand img").lazyload({effect:"fadeIn",failure_limit:Math.max(e(".iehand img").length-1,0),effectspeed:900,load:t})}})

jQuery(function(e){if(e(".pagwrap").attr("id")=='nopagination' && e(".emgclearfix").hasClass("emgpagntn")){alert('You cannot use gallery with pagination in the same page with grid gallery or filterable media.');e(".easycontainer, .emgpagntn, #filters").hide();return false;}})

/*
	StyleSwitcher script from  A List Apart
	Authored by Paul Sowden and Peter-Paul Koch
	http://www.alistapart.com/articles/alternate/
*/
function easyActiveStyleSheet(e){var t,n,r;for(t=0;n=document.getElementsByTagName("link")[t];t++){if(n.getAttribute("rel").indexOf("style")!=-1&&n.getAttribute("title")){n.disabled=true;if(n.getAttribute("title")==e)n.disabled=false}}}function getActiveStyleSheet(){var e,t;for(e=0;t=document.getElementsByTagName("link")[e];e++){if(t.getAttribute("rel").indexOf("style")!=-1&&t.getAttribute("title")&&!t.disabled)return t.getAttribute("title")}return null}function getPreferredStyleSheet(){var e,t;for(e=0;t=document.getElementsByTagName("link")[e];e++){if(t.getAttribute("rel").indexOf("style")!=-1&&t.getAttribute("rel").indexOf("alt")==-1&&t.getAttribute("title"))return t.getAttribute("title")}return null} easyActiveStyleSheet(EasyM.defstyle);