define("ydcore:widget/ui/vcode/vcode.js",function(a,t,u){var c=a("ydcommon:widget/ui/lib/jquery/jquery.js"),e={_url:"/customer/interface/commentvcode",_count:0,_callBack:c.Callbacks("unique memory"),_ajaxObj:null,refresh:function(){var a=this;a._ajaxObj&&a._ajaxObj.abort&&(a._ajaxObj.abort(),a._ajaxObj=null),a._count++,a._ajaxObj=c.ajax({url:a._url,method:"GET",cache:!1,dataType:"json",data:{type:1,count:a._count}}).done(function(t){a._callBack.fire(t.data&&t.data.imgurl?{status:0,req_count:a._count,url:t.data.imgurl}:{status:1,req_count:a._count,url:""}),a._ajaxObj=null
})},register:function(a){var t=this;return c.isFunction(a)?(t._callBack.add(a),!0):!1}};u.exports=e});
;define("ydcore:widget/ui/slide/slide.js",function(i,t,a){function s(i){this.defaultConfig={el:"banner",playSpeed:5e3,playType:"opacity",playNavClass:"play-nav",customPlayMethod:null},this.config=e.extend(!0,this.defaultConfig,i||{}),this.init.call(this)}var e=i("ydcommon:widget/ui/lib/jquery/jquery.js");s.prototype={init:function(){this._cache(),this._dynCalSize(),this._autoPlay(),this._initEvent()},_initEvent:function(){var i=this;e(this.imgUl).on("mouseover",e.proxy(this.stopPlay,this)),e(this.imgUl).on("mouseout",e.proxy(this._autoPlay,this)),this.navUl.delegate("li","mouseover",function(){var t=e(this),a=t.attr("data-idx");
i.nowPage!=a&&(i.stopPlay(),i.lastPage=i.nowPage,i.nowPage=a,i._play())})},stopPlay:function(){this.autoPlayTimer&&(clearInterval(this.autoPlayTimer),this.autoPlayTimer=null)},_autoPlay:function(){var i=this,t=this.config;i.stopPlay(),this.autoPlayTimer=setInterval(function(){i.next()},t.playSpeed)},_cache:function(){var i=this.config,t=null;i.el="string"===e.type(i.el)?e("#"+i.el):i.el,t=i.el.children("ul"),this.imgUl=t[0],this.imgList=e(this.imgUl).children("li"),this.totalPage=this.imgList.length,this.nowPage=1,this.lastPage=null,this.autoPlayTimer=null,t.length<2&&this._createNavUl()
},_dynCalSize:function(){var i=this.config,t=i.playType,a=e(this.imgUl),s=e(this.imgList[0]);"horizontal"===t&&(this.liWidth=s.width(),a.css("width",this.liWidth*this.totalPage)),"vertical"===t&&(this.liHeight=s.height(),a.css("height",this.liHeight*this.totalPage))},_createNavUl:function(){for(var i=this.config,t="",a=0;a<this.totalPage;a++){var s=a+1;t+='<li data-idx="'+s+'"><a href="javascript:void(0);">'+s+"</a></li>"}t='<ul class="'+i.playNavClass+'">'+t+"</ul>",this.navUl=e(t),this.navList=this.navUl.children("li"),i.el.append(this.navUl),e(this.navList[0]).addClass("cur")
},next:function(){this.config;this.lastPage=this.nowPage,this.nowPage++,this.nowPage>this.totalPage&&(this.nowPage=1,e(this).trigger("onPlayLast")),this._play()},pre:function(){this.config;this.lastPage=this.nowPage,this.nowPage--,this.nowPage<1&&(this.nowPage=this.totalPage,e(this).trigger("onPlayFirst")),this._play()},_play:function(){var i=this,t=this.config,a=e(this.imgList[this.nowPage-1]).find("img");if(e(this).trigger({type:"onSwitchBefore",curImg:a}),e.isFunction(t.customPlayMethod))t.customPlayMethod.call(i);
else switch(t.playType){case"base":i._basePlay();break;case"opacity":i._opacityPlay();break;case"vertical":i._verticalPlay();break;case"horizontal":i._horizontalPlay();break;default:i._basePlay()}i._focusNav(),e(this).trigger({type:"onSwitchAfter",curImg:a})},_basePlay:function(){var i=(this.config,this.imgList);i.each(function(){e(this).hide()}),e(i[this.nowPage-1]).show()},_opacityPlay:function(){var i=this,t=(this.config,this.imgList),a=e(t[i.nowPage-1]);a.css("opacity",1),t.each(function(s){var n=e(t[s]);
n.stop(),s!==i.nowPage-1&&n.animate({opacity:0},"normal","swing",function(){a.css("zIndex",9),n.css("zIndex",1)})})},_horizontalPlay:function(){var i=(this.config,this.nowPage),t=e(this.imgUl),a=-(this.liWidth*(i-1));t.stop(),t.animate({left:a})},_verticalPlay:function(){var i=(this.config,this.nowPage),t=e(this.imgUl),a=-(this.liHeight*(i-1));t.stop(),t.animate({top:a})},_focusNav:function(){var i=(this.config,this.navList);i.each(function(){e(this).removeClass("cur")}),e(i[this.nowPage-1]).addClass("cur")
}},a.exports.slide=s});
;define("ydcore:widget/ui/lazy_load/lazy_load.js",function(a,t,i){function o(a){this.defaultConfig={lazyLoadAttr:"data-src",preloadHeight:0,loadedCallback:null,lazyLoadBg:!0,lazyLoadBgClass:"lazybg"},this.config=n.extend(!0,this.defaultConfig,a||{}),this.init.call(this)}{var n=a("ydcommon:widget/ui/lib/jquery/jquery.js"),e=a("ydcommon:widget/ui/lib/browser/browser.js");6==e.ie?!0:!1}o.prototype={init:function(){this._cache(),this._initEvent(),this.acitonLazy()},_initEvent:function(){{var a=this;this.config
}this.acitonLazy=n.proxy(a._lazy,a),n(window).on("scroll",a.acitonLazy),n(window).on("resize",a.acitonLazy),n(window).on("load",a.acitonLazy),n(a).on("afterLoaded",function(t){a._afterLoaded(t.img,t.loadType)})},_cache:function(){this.lazyImgs=this._getLazyImgs(),this.lazyImgsLen=this.lazyImgs.length,this.acitonLazy=null},_getLazyImgs:function(){var a=this.config,t=[],i=null;return n("img").each(function(){i=n(this),i.attr(a.lazyLoadAttr)&&t.push(i)}),a.lazyLoadBg&&n("."+a.lazyLoadBgClass).each(function(){i=n(this),i.attr(a.lazyLoadAttr)&&t.push(i)
}),t},_lazy:function(){var a=this,t=this.config,i=t.lazyLoadAttr,o=t.preloadHeight,e=n(window),s=e.scrollTop(),l=e.innerHeight(),d=s+l+o,r=s-o;n.each(this.lazyImgs,function(o,e){var s=e.offset().top,l=s+e.innerHeight(),c=e.attr(i);d>s&&l>r&&c&&(e.hasClass(t.lazyLoadBgClass)?(e.css("background-image","url("+c+")"),e.removeAttr(i),a.lazyImgsLen--,n(a).trigger({type:"afterLoaded",img:e,loadType:"bg"})):(e.css("display","none"),e.attr("src",c),e.removeAttr(i),a.lazyImgsLen--,n(a).trigger({type:"afterLoaded",img:e,loadType:"img"})))
}),a.lazyImgsLen||a._dispose()},_dispose:function(){n(window).off("scroll",this.acitonLazy),n(window).off("resize",this.acitonLazy)},_afterLoaded:function(a,t){var i=this.config;n.isFunction(i.loadedCallback)?i.loadedCallback(a,t):"img"==t&&a.fadeIn("slow")}},n.extend({lazyload:function(a){return new o(a)}}),i.exports.lazyLoad=o});
;define("ydcore:widget/ui/placeholder/placeholder.js",function(e,a,t){var l,r;l=r=e("ydcommon:widget/ui/lib/jquery/jquery.js"),function(e,a,t){function l(e){var a={},l=/^jQuery\d+$/;return t.each(e.attributes,function(e,t){t.specified&&!l.test(t.name)&&(a[t.name]=t.value)}),a}function r(e,a){var l=this,r=t(l);if(l.value==r.attr("placeholder")&&r.hasClass("placeholder"))if(r.data("placeholder-password")){if(r=r.hide().next().show().attr("id",r.removeAttr("id").data("placeholder-id")),e===!0)return r[0].value=a;
r.focus()}else l.value="",r.removeClass("placeholder"),l==d()&&l.select()}function o(){var e,a=this,o=t(a),d=this.id;if(""==a.value){if("password"==a.type){if(!o.data("placeholder-textinput")){try{e=o.clone().attr({type:"text"})}catch(c){e=t("<input>").attr(t.extend(l(this),{type:"text"}))}e.removeAttr("name").data({"placeholder-password":o,"placeholder-id":d}).bind("focus.placeholder",r),o.data({"placeholder-textinput":e,"placeholder-id":d}).before(e)}o=o.removeAttr("id").hide().prev().attr("id",d).show()
}o.addClass("placeholder"),o[0].value=o.attr("placeholder")}else o.removeClass("placeholder")}function d(){try{return a.activeElement}catch(e){}}var c,i,n="[object OperaMini]"==Object.prototype.toString.call(e.operamini),u="placeholder"in a.createElement("input")&&!n,p="placeholder"in a.createElement("textarea")&&!n,h=t.fn,s=t.valHooks,v=t.propHooks;u&&p?(i=h.placeholder=function(){return this},i.input=i.textarea=!0):(i=h.placeholder=function(){var e=this;return e.filter((u?"textarea":":input")+"[placeholder]").not(".placeholder").bind({"focus.placeholder":r,"blur.placeholder":o}).data("placeholder-enabled",!0).trigger("blur.placeholder"),e
},i.input=u,i.textarea=p,c={get:function(e){var a=t(e),l=a.data("placeholder-password");return l?l[0].value:a.data("placeholder-enabled")&&a.hasClass("placeholder")?"":e.value},set:function(e,a){var l=t(e),c=l.data("placeholder-password");return c?c[0].value=a:l.data("placeholder-enabled")?(""==a?(e.value=a,e!=d()&&o.call(e)):l.hasClass("placeholder")?r.call(e,!0,a)||(e.value=a):e.value=a,l):e.value=a}},u||(s.input=c,v.value=c),p||(s.textarea=c,v.value=c),t(function(){t(a).delegate("form","submit.placeholder",function(){var e=t(".placeholder",this).each(r);
setTimeout(function(){e.each(o)},10)})}),t(e).bind("beforeunload.placeholder",function(){t(".placeholder").each(function(){this.value=""})}))}(this,document,r),t.exports=l});