/*
 FastClick: polyfill to remove click delays on browsers with touch UIs.

 @version 0.6.1
 @codingstandard ftlabs-jsv2
 @copyright The Financial Times Limited [All Rights Reserved]
 @license MIT License (see LICENSE.txt)
*/
function FastClick(a){var d,b=this;this.trackingClick=false;this.trackingClickStart=0;this.targetElement=null;this.lastTouchIdentifier=this.touchStartY=this.touchStartX=0;this.layer=a;if(!a||!a.nodeType)throw new TypeError("Layer must be a document node");this.onClick=function(){return FastClick.prototype.onClick.apply(b,arguments)};this.onMouse=function(){return FastClick.prototype.onMouse.apply(b,arguments)};this.onTouchStart=function(){return FastClick.prototype.onTouchStart.apply(b,arguments)};
this.onTouchEnd=function(){return FastClick.prototype.onTouchEnd.apply(b,arguments)};this.onTouchCancel=function(){return FastClick.prototype.onTouchCancel.apply(b,arguments)};if(typeof window.ontouchstart!=="undefined"){if(this.deviceIsAndroid){a.addEventListener("mouseover",this.onMouse,true);a.addEventListener("mousedown",this.onMouse,true);a.addEventListener("mouseup",this.onMouse,true)}a.addEventListener("click",this.onClick,true);a.addEventListener("touchstart",this.onTouchStart,false);a.addEventListener("touchend",
this.onTouchEnd,false);a.addEventListener("touchcancel",this.onTouchCancel,false);if(!Event.prototype.stopImmediatePropagation){a.removeEventListener=function(c,e,f){var g=Node.prototype.removeEventListener;c==="click"?g.call(a,c,e.hijacked||e,f):g.call(a,c,e,f)};a.addEventListener=function(c,e,f){var g=Node.prototype.addEventListener;c==="click"?g.call(a,c,e.hijacked||(e.hijacked=function(h){h.propagationStopped||e(h)}),f):g.call(a,c,e,f)}}if(typeof a.onclick==="function"){d=a.onclick;a.addEventListener("click",
function(c){d(c)},false);a.onclick=null}}}FastClick.prototype.deviceIsAndroid=navigator.userAgent.indexOf("Android")>0;FastClick.prototype.deviceIsIOS=/iP(ad|hone|od)/.test(navigator.userAgent);FastClick.prototype.deviceIsIOS4=FastClick.prototype.deviceIsIOS&&/OS 4_\d(_\d)?/.test(navigator.userAgent);FastClick.prototype.deviceIsIOSWithBadTarget=FastClick.prototype.deviceIsIOS&&/OS ([6-9]|\d{2})_\d/.test(navigator.userAgent);
FastClick.prototype.needsClick=function(a){switch(a.nodeName.toLowerCase()){case "button":case "input":if(this.deviceIsIOS&&a.type==="file")return true;return a.disabled;case "label":case "video":return true;default:return/\bneedsclick\b/.test(a.className)}};
FastClick.prototype.needsFocus=function(a){switch(a.nodeName.toLowerCase()){case "textarea":case "select":return true;case "input":switch(a.type){case "button":case "checkbox":case "file":case "image":case "radio":case "submit":return false}return!a.disabled&&!a.readOnly;default:return/\bneedsfocus\b/.test(a.className)}};
FastClick.prototype.sendClick=function(a,d){var b,c;document.activeElement&&document.activeElement!==a&&document.activeElement.blur();c=d.changedTouches[0];b=document.createEvent("MouseEvents");b.initMouseEvent("click",true,true,window,1,c.screenX,c.screenY,c.clientX,c.clientY,false,false,false,false,0,null);b.forwardedTouchEvent=true;a.dispatchEvent(b)};FastClick.prototype.focus=function(a){var d;if(this.deviceIsIOS&&a.setSelectionRange){d=a.value.length;a.setSelectionRange(d,d)}else a.focus()};
FastClick.prototype.updateScrollParent=function(a){var d,b;d=a.fastClickScrollParent;if(!d||!d.contains(a)){b=a;do{if(b.scrollHeight>b.offsetHeight){d=b;a.fastClickScrollParent=b;break}b=b.parentElement}while(b)}if(d)d.fastClickLastScrollTop=d.scrollTop};FastClick.prototype.getTargetElementFromEventTarget=function(a){if(a.nodeType===Node.TEXT_NODE)return a.parentNode;return a};
FastClick.prototype.onTouchStart=function(a){var d,b,c;d=this.getTargetElementFromEventTarget(a.target);b=a.targetTouches[0];if(this.deviceIsIOS){c=window.getSelection();if(c.rangeCount&&!c.isCollapsed)return true;if(!this.deviceIsIOS4){if(b.identifier===this.lastTouchIdentifier){a.preventDefault();return false}this.lastTouchIdentifier=b.identifier;this.updateScrollParent(d)}}this.trackingClick=true;this.trackingClickStart=a.timeStamp;this.targetElement=d;this.touchStartX=b.pageX;this.touchStartY=
b.pageY;a.timeStamp-this.lastClickTime<200&&a.preventDefault();return true};FastClick.prototype.touchHasMoved=function(a){a=a.changedTouches[0];if(Math.abs(a.pageX-this.touchStartX)>10||Math.abs(a.pageY-this.touchStartY)>10)return true;return false};FastClick.prototype.findControl=function(a){if(a.control!==undefined)return a.control;if(a.htmlFor)return document.getElementById(a.htmlFor);return a.querySelector("button, input:not([type=hidden]), keygen, meter, output, progress, select, textarea")};
FastClick.prototype.onTouchEnd=function(a){var d,b,c=this.targetElement;if(this.touchHasMoved(a)){this.trackingClick=false;this.targetElement=null}if(!this.trackingClick)return true;if(a.timeStamp-this.lastClickTime<200)return this.cancelNextClick=true;this.lastClickTime=a.timeStamp;d=this.trackingClickStart;this.trackingClick=false;this.trackingClickStart=0;if(this.deviceIsIOSWithBadTarget){b=a.changedTouches[0];c=document.elementFromPoint(b.pageX-window.pageXOffset,b.pageY-window.pageYOffset)}b=
c.tagName.toLowerCase();if(b==="label"){if(d=this.findControl(c)){this.focus(c);if(this.deviceIsAndroid)return false;c=d}}else if(this.needsFocus(c)){if(a.timeStamp-d>100||this.deviceIsIOS&&window.top!==window&&b==="input"){this.targetElement=null;return false}this.focus(c);if(!this.deviceIsIOS4||b!=="select"){this.targetElement=null;a.preventDefault()}return false}if(this.deviceIsIOS&&!this.deviceIsIOS4)if((d=c.fastClickScrollParent)&&d.fastClickLastScrollTop!==d.scrollTop)return true;if(!this.needsClick(c)){a.preventDefault();
var e=this;setTimeout(function(){e.sendClick(c,a)},0)}return false};FastClick.prototype.onTouchCancel=function(){this.trackingClick=false;this.targetElement=null};FastClick.prototype.onMouse=function(a){if(!this.targetElement)return true;if(a.forwardedTouchEvent)return true;if(!a.cancelable)return true;if(!this.needsClick(this.targetElement)||this.cancelNextClick){if(a.stopImmediatePropagation)a.stopImmediatePropagation();else a.propagationStopped=true;a.stopPropagation();a.preventDefault();return false}return true};
FastClick.prototype.onClick=function(a){if(this.trackingClick){this.targetElement=null;this.trackingClick=false;return true}if(a.target.type==="submit"&&a.detail===0)return true;a=this.onMouse(a);if(!a)this.targetElement=null;return a};
FastClick.prototype.destroy=function(){var a=this.layer;if(this.deviceIsAndroid){a.removeEventListener("mouseover",this.onMouse,true);a.removeEventListener("mousedown",this.onMouse,true);a.removeEventListener("mouseup",this.onMouse,true)}a.removeEventListener("click",this.onClick,true);a.removeEventListener("touchstart",this.onTouchStart,false);a.removeEventListener("touchend",this.onTouchEnd,false);a.removeEventListener("touchcancel",this.onTouchCancel,false)};FastClick.attach=function(a){return new FastClick(a)};
typeof define!=="undefined"&&define.amd&&define(function(){return FastClick});if(typeof module!=="undefined"&&module.exports){module.exports=FastClick.attach;module.exports.FastClick=FastClick};
